markdown: kramdown
theme: minimal
title: OCP Events
description: Information about partner facing events for MSUS OCP Partners
google_analytics: null

collections:
  events:
    output: true
  groups:
    output: true
  states:
    output: true
    permalink: /states/:path/
  regions:
    output: true
    permalink: /regions/:path/
  topics:
    output: true
    permalink: /topics/:path/
    
defaults:
  -
    scope:
      path: "" 
      type: "topics"
    values:
      layout: "topic"
  -
    scope:
      path: "" 
      type: "regions"
    values:
      layout: "region"
  -
    scope:
      path: "" 
      type: "states"
    values:
      layout: "state"
